# Generated by Django 5.0.1 on 2026-07-07 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(choices=[('active_users', 'Active Users'), ('experiments_per_hour', 'Experiments Per Hour'), ('avg_response_time', 'Avg Response Time (s)'), ('error_rate', 'Error Rate (%)')], db_index=True, max_length=50)),
                ('metric_value', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['metric_name', 'recorded_at'], name='admin_panel_metric__77d607_idx')],
            },
        ),
    ]
