# Generated by Django 5.0.1 on 2026-07-07 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_systemmetric'),
        ('experiments', '0001_initial'),
        ('privacy_tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_reports', to='experiments.experiment')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL)),
                ('technique', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='privacy_tools.privacytechnique')),
            ],
            options={
                'verbose_name': 'Experiment Error Report',
                'verbose_name_plural': 'Experiment Error Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
