from django.shortcuts import render, redirect, get_object_or_404
from django.db import models
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponse, JsonResponse
from django.core.paginator import Paginator
from django.views.decorators.http import require_POST
from django.utils import timezone
from .models import Report, ReportSchedule, ReportTemplate
from .forms import ReportGenerationForm, ReportScheduleForm, ReportTemplateForm
from experiments.models import Experiment
import json
import csv
import logging
from datetime import datetime
from .pdf_generator import PDFReportGenerator

report_logger = logging.getLogger('reports')

@login_required
def report_list(request):
    """List all user's reports"""
    reports = Report.objects.filter(user=request.user).order_by('-created_at')
    
    # Pagination
    paginator = Paginator(reports, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    
    context = {
        'page_obj': page_obj,
        'reports': page_obj
    }
    return render(request, 'reports/report_list.html', context)

@login_required
def report_generate(request):
    """Generate new report"""
    if request.method == 'POST':
        form = ReportGenerationForm(request.POST, user=request.user)
        if form.is_valid():
            report = form.save(commit=False)
            report.user = request.user
            
            # Get selected experiments
            experiments = form.cleaned_data['experiments']
            
            # Generate report content
            content = generate_report_content(experiments, report.report_type)
            report.content = content
            
            # Generate summary
            report.summary = generate_report_summary(experiments)
            
            report.save()
            form.save_m2m()
            
            # Apply template sections if a template was selected
            if report.template and report.template.sections:
                apply_template_to_report(report)
            
            # Generate file if needed
            if report.file_format == 'pdf':
                PDFReportGenerator(report).generate()
            elif report.file_format in ['csv', 'json']:
                generate_report_file(report)
            
            report_logger.info(
                "Report %s generated by %s (type=%s, format=%s, experiments=%d)",
                report.pk, request.user.username,
                report.report_type, report.file_format, experiments.count(),
            )
            messages.success(request, 'Report generated successfully!')
            return redirect('reports:detail', pk=report.pk)
    else:
        form = ReportGenerationForm(user=request.user)
    
    context = {
        'form': form,
        'completed_experiments': Experiment.objects.filter(
            user=request.user,
            status='completed'
        ).order_by('-created_at')
    }
    return render(request, 'reports/report_generate.html', context)

def generate_report_content(experiments, report_type):
    """Generate structured report content based on experiments"""
    sections = {}
    
    # 1. Executive Summary
    sections['executive_summary'] = generate_report_summary(experiments)
    
    # 2. Methodology
    technique_groups = {}
    for exp in experiments:
        tech = exp.privacy_technique
        tech_name = tech.name
        if tech_name not in technique_groups:
            technique_groups[tech_name] = {
                'name': tech.name,
                'type': tech.get_technique_type_display(),
                'security_level': tech.security_level,
                'complexity': tech.complexity,
                'description': tech.description,
                'algorithm_details': tech.algorithm_details,
                'parameters': tech.parameters,
                'experiment_count': 0,
            }
        technique_groups[tech_name]['experiment_count'] += 1
    
    sections['methodology'] = list(technique_groups.values())
    
    # 3. Results (per-experiment with all metrics)
    results = []
    for exp in experiments:
        exp_data = {
            'id': exp.id,
            'name': exp.name,
            'technique': exp.privacy_technique.name,
            'dataset': exp.dataset.name,
            'status': exp.status,
            'privacy_score': exp.privacy_score,
            'execution_time': exp.execution_time,
            'accuracy': exp.accuracy,
            'throughput': exp.throughput,
            'anonymity_set_size': exp.anonymity_set_size,
            'metrics': exp.metrics,
            'configuration': exp.configuration,
            'created_at': exp.created_at.isoformat(),
            'completed_at': exp.completed_at.isoformat() if exp.completed_at else None,
            'error_message': exp.error_message if exp.status == 'failed' else None,
        }
        results.append(exp_data)
    sections['results'] = results
    
    # 4. Comparison (side-by-side with rankings) – only for multi-experiment reports
    if len(experiments) > 1:
        # Ranking by privacy score (descending)
        ranked = sorted(experiments, key=lambda e: e.privacy_score or 0, reverse=True)
        ranking = []
        for i, exp in enumerate(ranked, 1):
            ranking.append({
                'rank': i,
                'experiment_id': exp.id,
                'name': exp.name,
                'technique': exp.privacy_technique.name,
                'privacy_score': exp.privacy_score,
                'accuracy': exp.accuracy,
                'throughput': exp.throughput,
                'execution_time': exp.execution_time,
            })
        sections['comparison'] = {
            'ranking': ranking,
            'best_privacy': ranked[0].id if ranked else None,
            'fastest': min(experiments, key=lambda e: e.execution_time or float('inf')).id if experiments else None,
            'best_accuracy': max(experiments, key=lambda e: e.accuracy or 0).id if experiments else None,
            'best_throughput': max(experiments, key=lambda e: e.throughput or 0).id if experiments else None,
        }
    
    # 5. Recommendations (data-driven)
    recommendations = []
    if experiments:
        # Best for privacy
        best_privacy = max(
            [e for e in experiments if e.privacy_score is not None],
            key=lambda e: e.privacy_score,
            default=None
        )
        if best_privacy:
            recommendations.append({
                'title': 'Best for Privacy',
                'experiment_id': best_privacy.id,
                'experiment_name': best_privacy.name,
                'technique': best_privacy.privacy_technique.name,
                'value': f"Privacy Score: {best_privacy.privacy_score:.2f}",
            })
        # Best for performance (throughput)
        best_perf = max(
            [e for e in experiments if e.throughput is not None],
            key=lambda e: e.throughput,
            default=None
        )
        if best_perf:
            recommendations.append({
                'title': 'Best for Performance',
                'experiment_id': best_perf.id,
                'experiment_name': best_perf.name,
                'technique': best_perf.privacy_technique.name,
                'value': f"Throughput: {best_perf.throughput:.2f} tps",
            })
        # Fastest
        fastest = min(
            [e for e in experiments if e.execution_time is not None],
            key=lambda e: e.execution_time,
            default=None
        )
        if fastest:
            recommendations.append({
                'title': 'Fastest Execution',
                'experiment_id': fastest.id,
                'experiment_name': fastest.name,
                'technique': fastest.privacy_technique.name,
                'value': f"Time: {fastest.execution_time:.3f}s",
            })
        # Best accuracy
        best_accuracy = max(
            [e for e in experiments if e.accuracy is not None],
            key=lambda e: e.accuracy,
            default=None
        )
        if best_accuracy:
            recommendations.append({
                'title': 'Best Accuracy',
                'experiment_id': best_accuracy.id,
                'experiment_name': best_accuracy.name,
                'technique': best_accuracy.privacy_technique.name,
                'value': f"Accuracy: {best_accuracy.accuracy*100:.2f}%",
            })
    sections['recommendations'] = recommendations
    
    # 6. Raw Data (embedded CSV)
    if experiments:
        output = io.StringIO()
        fieldnames = ['name', 'technique', 'dataset', 'privacy_score', 
                     'execution_time', 'accuracy', 'throughput', 'anonymity_set_size']
        writer = csv.DictWriter(output, fieldnames=fieldnames)
        writer.writeheader()
        for exp in experiments:
            writer.writerow({
                'name': exp.name,
                'technique': exp.privacy_technique.name,
                'dataset': exp.dataset.name,
                'privacy_score': exp.privacy_score or 0,
                'execution_time': exp.execution_time or 0,
                'accuracy': exp.accuracy or 0,
                'throughput': exp.throughput or 0,
                'anonymity_set_size': exp.anonymity_set_size or 0,
            })
        sections['raw_data'] = output.getvalue()
    else:
        sections['raw_data'] = ''
    
    return json.dumps(sections, indent=2)

def generate_report_summary(experiments):
    """Generate summary statistics"""
    if not experiments:
        return "No experiments included in this report."
    
    total = experiments.count()
    avg_privacy = sum(e.privacy_score or 0 for e in experiments) / total
    avg_time = sum(e.execution_time or 0 for e in experiments) / total
    avg_accuracy = sum(e.accuracy or 0 for e in experiments) / total
    
    techniques = set(e.privacy_technique.name for e in experiments)
    
    summary = f"""
    Report Summary:
    - Total Experiments: {total}
    - Techniques Evaluated: {', '.join(techniques)}
    - Average Privacy Score: {avg_privacy:.2f}
    - Average Execution Time: {avg_time:.3f} seconds
    - Average Accuracy: {avg_accuracy:.4f}
    """
    
    return summary.strip()

def apply_template_to_report(report):
    """Filter report content sections based on template selection"""
    import json
    try:
        content_data = json.loads(report.content)
    except (json.JSONDecodeError, TypeError):
        return

    template = report.template
    allowed_sections = set(template.sections)

    section_key_map = {
        'summary': 'executive_summary',
        'methodology': 'methodology',
        'results': 'results',
        'comparison': 'comparison',
        'recommendations': 'recommendations',
        'raw': 'raw_data',
    }

    filtered = {}
    for section_key, data_key in section_key_map.items():
        if section_key in allowed_sections and data_key in content_data:
            filtered[data_key] = content_data[data_key]

    # Always include summary and raw for completeness, but nullify if not selected
    filtered['executive_summary'] = filtered.get('executive_summary', content_data.get('executive_summary', ''))
    filtered['raw_data'] = filtered.get('raw_data', content_data.get('raw_data', ''))

    # Ensure empty values for non-selected sections don't show
    for section_key, data_key in section_key_map.items():
        if section_key not in allowed_sections:
            filtered[data_key] = '' if data_key in ('executive_summary', 'raw_data') else []

    # Apply layout from template
    if template.layout:
        filtered['_layout'] = template.layout

    report.content = json.dumps(filtered, indent=2)
    report.save(update_fields=['content'])


def generate_report_file(report):
    """Generate downloadable report file"""
    import os
    from django.conf import settings
    
    experiments = report.experiments.all()
    filename = f"report_{report.id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.{report.file_format}"
    filepath = os.path.join(settings.MEDIA_ROOT, 'reports', filename)
    
    # Ensure directory exists
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    
    if report.file_format == 'csv':
        with open(filepath, 'w', newline='') as csvfile:
            fieldnames = ['name', 'technique', 'dataset', 'privacy_score', 
                         'execution_time', 'accuracy', 'throughput', 'anonymity_set_size']
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            
            writer.writeheader()
            for exp in experiments:
                writer.writerow({
                    'name': exp.name,
                    'technique': exp.privacy_technique.name,
                    'dataset': exp.dataset.name,
                    'privacy_score': exp.privacy_score or 0,
                    'execution_time': exp.execution_time or 0,
                    'accuracy': exp.accuracy or 0,
                    'throughput': exp.throughput or 0,
                    'anonymity_set_size': exp.anonymity_set_size or 0,
                })
    
    elif report.file_format == 'json':
        data = []
        for exp in experiments:
            data.append({
                'name': exp.name,
                'technique': exp.privacy_technique.name,
                'dataset': exp.dataset.name,
                'privacy_score': exp.privacy_score,
                'execution_time': exp.execution_time,
                'accuracy': exp.accuracy,
                'throughput': exp.throughput,
                'anonymity_set_size': exp.anonymity_set_size,
                'metrics': exp.metrics
            })
        
        with open(filepath, 'w') as jsonfile:
            json.dump(data, jsonfile, indent=2)
    
    report.file = f'reports/{filename}'
    report.save()

@login_required
def report_detail(request, pk):
    """View report details"""
    report = get_object_or_404(Report, pk=pk, user=request.user)
    
    # Parse content
    try:
        content_data = json.loads(report.content)
    except (json.JSONDecodeError, TypeError):
        content_data = {}
    
    # Backward compatibility: if content_data is a list (old format), wrap in new structure
    if isinstance(content_data, list):
        content_data = {
            'results': content_data,
            'raw_data': '',
            'executive_summary': '',
            'methodology': [],
            'recommendations': [],
        }
    
    context = {
        'report': report,
        'content_data': content_data,
        'experiments': report.experiments.all()
    }
    return render(request, 'reports/report_detail.html', context)

@login_required
def report_download(request, pk):
    """Download report file"""
    report = get_object_or_404(Report, pk=pk, user=request.user)
    
    if not report.file:
        messages.error(request, 'No file available for download.')
        return redirect('reports:detail', pk=pk)
    
    report_logger.info(
        "Report %s downloaded by %s (format=%s)",
        report.pk, request.user.username, report.file_format,
    )

    # Serve file
    if report.file_format == 'csv':
        content_type = 'text/csv'
    elif report.file_format == 'json':
        content_type = 'application/json'
    elif report.file_format == 'pdf':
        content_type = 'application/pdf'
    else:
        content_type = 'application/octet-stream'
    
    with open(report.file.path, 'rb') as f:
        response = HttpResponse(f.read(), content_type=content_type)
        response['Content-Disposition'] = f'attachment; filename="{report.file.name.split("/")[-1]}"'
        return response

@login_required
def report_delete(request, pk):
    """Delete report"""
    report = get_object_or_404(Report, pk=pk, user=request.user)
    
    if request.method == 'POST':
        # Delete file if exists
        if report.file:
            import os
            if os.path.isfile(report.file.path):
                os.remove(report.file.path)
        
        report.delete()
        messages.success(request, 'Report deleted successfully.')
        return redirect('reports:list')
    
    context = {'report': report}
    return render(request, 'reports/report_confirm_delete.html', context)


# ─── Report Schedule Views ────────────────────────────────────

@login_required
def schedule_list(request):
    """List all report schedules for current user"""
    schedules = ReportSchedule.objects.filter(user=request.user).order_by('-created_at')
    paginator = Paginator(schedules, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'schedules': page_obj,
    }
    return render(request, 'reports/report_schedule_list.html', context)


@login_required
def schedule_create(request):
    """Create a new report schedule"""
    if request.method == 'POST':
        form = ReportScheduleForm(request.POST, user=request.user)
        if form.is_valid():
            schedule = form.save(commit=False)
            schedule.user = request.user
            schedule.next_run = schedule.compute_next_run()
            schedule.save()
            form.save_m2m()
            report_logger.info(
                "Report schedule created: %s (user=%s, freq=%s)",
                schedule.name, request.user.username, schedule.schedule_frequency,
            )
            messages.success(request, f'Schedule "{schedule.name}" created successfully.')
            return redirect('reports:schedule_detail', pk=schedule.pk)
    else:
        form = ReportScheduleForm(user=request.user)

    context = {
        'form': form,
        'is_edit': False,
        'completed_experiments': Experiment.objects.filter(
            user=request.user, status='completed'
        ).order_by('-created_at'),
    }
    return render(request, 'reports/report_schedule_form.html', context)


@login_required
def schedule_edit(request, pk):
    """Edit an existing report schedule"""
    schedule = get_object_or_404(ReportSchedule, pk=pk, user=request.user)
    if request.method == 'POST':
        form = ReportScheduleForm(request.POST, instance=schedule, user=request.user)
        if form.is_valid():
            schedule = form.save(commit=False)
            schedule.next_run = schedule.compute_next_run()
            schedule.save()
            form.save_m2m()
            messages.success(request, f'Schedule "{schedule.name}" updated successfully.')
            return redirect('reports:schedule_detail', pk=schedule.pk)
    else:
        form = ReportScheduleForm(instance=schedule, user=request.user)

    context = {
        'form': form,
        'is_edit': True,
        'schedule': schedule,
        'completed_experiments': Experiment.objects.filter(
            user=request.user, status='completed'
        ).order_by('-created_at'),
    }
    return render(request, 'reports/report_schedule_form.html', context)


@login_required
def schedule_detail(request, pk):
    """View schedule details with history of generated reports"""
    schedule = get_object_or_404(ReportSchedule, pk=pk, user=request.user)
    generated_reports = schedule.generated_reports.all().order_by('-created_at')
    paginator = Paginator(generated_reports, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'schedule': schedule,
        'generated_reports': page_obj,
        'page_obj': page_obj,
    }
    return render(request, 'reports/report_schedule_detail.html', context)


@login_required
@require_POST
def schedule_toggle(request, pk):
    """Toggle schedule active/inactive"""
    schedule = get_object_or_404(ReportSchedule, pk=pk, user=request.user)
    schedule.is_active = not schedule.is_active
    schedule.save(update_fields=['is_active'])
    status = 'activated' if schedule.is_active else 'deactivated'
    messages.success(request, f'Schedule "{schedule.name}" {status}.')
    return redirect('reports:schedule_detail', pk=schedule.pk)


@login_required
@require_POST
def schedule_delete(request, pk):
    """Delete a report schedule"""
    schedule = get_object_or_404(ReportSchedule, pk=pk, user=request.user)
    name = schedule.name
    schedule.delete()
    messages.success(request, f'Schedule "{name}" deleted successfully.')
    return redirect('reports:schedule_list')


# ─── Report Template Views ────────────────────────────────────

@login_required
def template_list(request):
    """List all report templates available to the user"""
    templates = ReportTemplate.objects.filter(
        models.Q(is_public=True) | models.Q(user=request.user)
    ).order_by('-is_public', 'name')
    paginator = Paginator(templates, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'templates': page_obj,
    }
    return render(request, 'reports/report_template_list.html', context)


@login_required
def template_create(request):
    """Create a new report template"""
    if request.method == 'POST':
        form = ReportTemplateForm(request.POST)
        if form.is_valid():
            template = form.save(commit=False)
            template.user = request.user
            template.save()
            report_logger.info(
                "Report template created: %s (user=%s)",
                template.name, request.user.username,
            )
            messages.success(request, f'Template "{template.name}" created successfully.')
            return redirect('reports:template_list')
    else:
        form = ReportTemplateForm()

    context = {
        'form': form,
        'is_edit': False,
    }
    return render(request, 'reports/report_template_form.html', context)


@login_required
def template_edit(request, pk):
    """Edit an existing report template"""
    template = get_object_or_404(ReportTemplate, pk=pk)
    # Only owner or superuser can edit
    if template.user != request.user and not request.user.is_superuser:
        messages.error(request, 'You do not have permission to edit this template.')
        return redirect('reports:template_list')

    if request.method == 'POST':
        form = ReportTemplateForm(request.POST, instance=template)
        if form.is_valid():
            form.save()
            messages.success(request, f'Template "{template.name}" updated successfully.')
            return redirect('reports:template_list')
    else:
        form = ReportTemplateForm(instance=template)

    context = {
        'form': form,
        'is_edit': True,
        'template': template,
    }
    return render(request, 'reports/report_template_form.html', context)


@login_required
@require_POST
def template_delete(request, pk):
    """Delete a report template"""
    template = get_object_or_404(ReportTemplate, pk=pk)
    if template.user != request.user and not request.user.is_superuser:
        messages.error(request, 'You do not have permission to delete this template.')
        return redirect('reports:template_list')
    name = template.name
    template.delete()
    messages.success(request, f'Template "{name}" deleted successfully.')
    return redirect('reports:template_list')
