from django.core.management.base import BaseCommand
from django.utils import timezone
from reports.models import ReportSchedule, Report
from reports.views import generate_report_content, generate_report_summary, generate_report_file
from reports.pdf_generator import PDFReportGenerator
import logging

report_logger = logging.getLogger('reports')

class Command(BaseCommand):
    help = 'Process scheduled reports — checks next_run, generates reports, updates schedule'

    def handle(self, *args, **options):
        now = timezone.now()
        schedules = ReportSchedule.objects.filter(
            is_active=True,
            next_run__lte=now,
        )

        if not schedules.exists():
            self.stdout.write(self.style.SUCCESS('No scheduled reports due for processing.'))
            return

        for schedule in schedules:
            self._process_schedule(schedule)

        self.stdout.write(self.style.SUCCESS(f'Processed {schedules.count()} scheduled report(s).'))

    def _process_schedule(self, schedule):
        experiments = schedule.experiments.all()
        if not experiments:
            self.stdout.write(self.style.WARNING(
                f'Schedule "{schedule.name}" has no experiments. Skipping.'
            ))
            schedule.next_run = schedule.compute_next_run()
            schedule.save(update_fields=['next_run'])
            return

        report = Report(
            title=f"{schedule.name} - {timezone.now().strftime('%Y-%m-%d %H:%M')}",
            report_type=schedule.report_type,
            user=schedule.user,
            file_format=schedule.file_format,
            schedule=schedule,
        )

        content = generate_report_content(experiments, schedule.report_type)
        report.content = content
        report.summary = generate_report_summary(experiments)
        report.save()
        report.experiments.set(experiments)

        if schedule.file_format == 'pdf':
            PDFReportGenerator(report).generate()
        elif schedule.file_format in ['csv', 'json']:
            generate_report_file(report)

        report_logger.info(
            "Scheduled report %s auto-generated by schedule '%s' (user=%s)",
            report.pk, schedule.name, schedule.user.username,
        )

        schedule.last_run = timezone.now()
        schedule.next_run = schedule.compute_next_run()
        schedule.save(update_fields=['last_run', 'next_run'])

        self.stdout.write(self.style.SUCCESS(
            f'  Generated report #{report.pk} from schedule "{schedule.name}"'
        ))
