from django.core.management.base import BaseCommand
from django.db import transaction


class Command(BaseCommand):
    help = 'Seed 3 default report templates: Full Report, Executive Summary, Technical Deep Dive'

    def handle(self, *args, **options):
        from reports.models import ReportTemplate

        defaults = [
            {
                'name': 'Full Report',
                'description': 'Complete report with all sections — executive summary, methodology, results, comparison, recommendations, and raw data.',
                'is_public': True,
                'sections': ['summary', 'methodology', 'results', 'comparison', 'recommendations', 'raw'],
                'layout': {
                    'header_text': 'Full Analysis Report',
                    'footer_text': 'Generated by Privacy Platform — Full Report',
                    'primary_color': '#0d6efd',
                    'logo_url': '',
                },
            },
            {
                'name': 'Executive Summary',
                'description': 'High-level overview with key findings, recommendations, and comparison highlights. Ideal for stakeholders.',
                'is_public': True,
                'sections': ['summary', 'comparison', 'recommendations'],
                'layout': {
                    'header_text': 'Executive Summary',
                    'footer_text': 'Generated by Privacy Platform — Executive Summary',
                    'primary_color': '#198754',
                    'logo_url': '',
                },
            },
            {
                'name': 'Technical Deep Dive',
                'description': 'Detailed technical report with methodology, per-experiment metrics, configuration parameters, and raw data for analysis.',
                'is_public': True,
                'sections': ['methodology', 'results', 'recommendations', 'raw'],
                'layout': {
                    'header_text': 'Technical Deep Dive',
                    'footer_text': 'Generated by Privacy Platform — Technical Report',
                    'primary_color': '#6f42c1',
                    'logo_url': '',
                },
            },
        ]

        created_count = 0
        existing_count = 0

        with transaction.atomic():
            for data in defaults:
                template, created = ReportTemplate.objects.get_or_create(
                    name=data['name'],
                    defaults={
                        'description': data['description'],
                        'is_public': data['is_public'],
                        'sections': data['sections'],
                        'layout': data['layout'],
                    },
                )
                if created:
                    created_count += 1
                    self.stdout.write(self.style.SUCCESS(f'Created: {template.name}'))
                else:
                    existing_count += 1
                    self.stdout.write(self.style.WARNING(f'Already exists: {template.name}'))

        self.stdout.write(
            self.style.SUCCESS(
                f'Done. Created {created_count}, already existing {existing_count} default template(s).'
            )
        )
