# Generated by Django 5.0.1 on 2026-01-24 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PrivacyTechnique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "technique_type",
                    models.CharField(
                        choices=[
                            ("ring_signature", "Ring Signatures"),
                            ("zkp", "Zero-Knowledge Proofs"),
                            ("smpc", "Secure Multi-Party Computation"),
                            ("tee", "Trusted Execution Environments"),
                            ("mixer", "Cryptocurrency Mixers"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("algorithm_details", models.TextField()),
                ("parameters", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("complexity", models.CharField(blank=True, max_length=50)),
                (
                    "security_level",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "privacy_techniques",
                "ordering": ["technique_type", "name"],
            },
        ),
    ]
