# Generated by Django 5.0.1 on 2026-01-24 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("experiments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Experiment"),
                            ("comparison", "Comparison Report"),
                            ("summary", "Summary Report"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("summary", models.TextField(blank=True)),
                (
                    "file_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("csv", "CSV"), ("json", "JSON")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="reports/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "experiments",
                    models.ManyToManyField(
                        related_name="reports", to="experiments.experiment"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
