# Generated by Django 5.0.1 on 2026-07-06 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('report_type', models.CharField(choices=[('single', 'Single Experiment'), ('comparison', 'Comparison Report'), ('summary', 'Summary Report')], max_length=20)),
                ('file_format', models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON')], default='pdf', max_length=10)),
                ('schedule_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('schedule_day', models.IntegerField(blank=True, help_text='Day of week (0=Mon..6=Sun) for weekly, day of month (1-31) for monthly', null=True)),
                ('filter_criteria', models.JSONField(blank=True, default=dict, null=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_generate', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experiments', models.ManyToManyField(blank=True, to='experiments.experiment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to='reports.reportschedule'),
        ),
    ]
