# Generated by Django 5.0.1 on 2026-07-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_add_report_share_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='file_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('xlsx', 'Excel (XLSX)'), ('zip', 'ZIP (All Formats)')], default='pdf', max_length=10),
        ),
        migrations.AlterField(
            model_name='reportschedule',
            name='file_format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('csv', 'CSV'), ('json', 'JSON'), ('xlsx', 'Excel (XLSX)'), ('zip', 'ZIP (All Formats)')], default='pdf', max_length=10),
        ),
    ]
