# Generated by Django 5.0.1 on 2026-07-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_file_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
