# Generated by Django 5.0.1 on 2026-07-08 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(choices=[('experiment_completed', 'Experiment Completed'), ('experiment_failed', 'Experiment Failed'), ('dataset_approved', 'Dataset Approved'), ('dataset_rejected', 'Dataset Rejected'), ('report_ready', 'Report Ready'), ('report_shared', 'Report Shared'), ('comparison_shared', 'Comparison Shared')], max_length=30)),
                ('description', models.TextField()),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='idx_notif_recipient_read'), models.Index(fields=['recipient', 'created_at'], name='idx_notif_recipient_date')],
            },
        ),
    ]
