# Generated by Django 5.0.1 on 2026-07-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(choices=[('experiment_completed', 'Experiment Completed'), ('experiment_failed', 'Experiment Failed'), ('dataset_approved', 'Dataset Approved'), ('dataset_rejected', 'Dataset Rejected'), ('dataset_pending', 'Dataset Pending Approval'), ('report_ready', 'Report Ready'), ('report_shared', 'Report Shared'), ('comparison_shared', 'Comparison Shared')], max_length=30),
        ),
    ]
