# Generated by Django 5.0.1 on 2026-07-08 11:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0002_experiment_configuration_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_access_count', models.IntegerField(blank=True, null=True)),
                ('permissions', models.CharField(choices=[('view_only', 'View Only'), ('download', 'Can Download')], default='view_only', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
                ('is_revoked', models.BooleanField(default=False)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='experiments.experiment')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_experiments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'experiment_shares',
                'ordering': ['-created_at'],
            },
        ),
    ]
